<?xml version="1.0" encoding="UTF-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <material name="green">
        <color rgba="0.0 0.5 0.0 1.0"/>
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
    </material>

    <material name="black">
        <color rgba="0.05 0.05 0.05 1.0"/>
    </material>
    
    <xacro:macro name="box_inertia" params="l w h m o_xyz o_rpy">
        <inertial>
                <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
                <mass value="${m}"/>
                <inertia ixx="${m*(w*w+h*h)/12.0}" ixy="0.0" ixz="0.0" 
                         iyy="${m*(l*l+h*h)/12.0}" iyz="0.0" 
                         izz="${m*(w*w+l*l)/12.0}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="r l m o_xyz o_rpy">
        <inertial>
                <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
                <mass value="${m}"/>
                <inertia ixx="${m*(3*r*r+l*l)/12.0}" ixy="0.0" ixz="0.0" 
                         iyy="${m*(l*l+3*r*r)/12.0}" iyz="0.0" 
                         izz="${m*(r*r)/2.0}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="r m o_xyz o_rpy">
        <inertial>
                <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
                <mass value="${m}"/>
                <inertia ixx="${2*m*r*r/5.0}" ixy="0.0" ixz="0.0" 
                         iyy="${2*m*r*r/5.0}" iyz="0.0" 
                         izz="${2*m*r*r/5.0}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="read_model_data" params="robot_parameters_file">
        <!-- Read .yaml files from disk, load content into properties -->
        <xacro:property name="config_robot_parameters" value="${xacro.load_yaml(robot_parameters_file)}"/>
        <!-- Extract subsections from yaml dictionaries -->
        <xacro:property name="base_properties" value="${config_robot_parameters['robot_parameters']['base']}"/>
        <xacro:property name="wheel_properties" value="${config_robot_parameters['robot_parameters']['wheel']}"/>
        <xacro:property name="steering_properties" value="${config_robot_parameters['robot_parameters']['steering']}"/>
        <!-- Vehicle Properties -->
        <xacro:property name="base_length" value="${base_properties['base_length']}" scope="parent"/>
        <xacro:property name="base_width" value="${base_properties['base_width']}" scope="parent"/>
        <xacro:property name="base_height" value="${base_properties['base_height']}" scope="parent"/>
        <xacro:property name="base_density" value="${base_properties['base_density']}" scope="parent"/>
        <xacro:property name="wheel_radius" value="${wheel_properties['wheel_radius']}" scope="parent"/>
        <xacro:property name="wheel_width" value="${wheel_properties['wheel_width']}" scope="parent"/>
        <xacro:property name="wheel_density" value="${wheel_properties['wheel_density']}" scope="parent"/>
        <xacro:property name="max_steering_angle" value="${steering_properties['max_steering_angle']}" scope="parent"/>
        <xacro:property name="max_steering_angular_velocity" value="${steering_properties['max_steering_angular_velocity']}" scope="parent"/>
        <xacro:property name="max_steering_effort" value="${steering_properties['max_steering_effort']}" scope="parent"/>
        <xacro:property name="max_velocity" value="${steering_properties['max_velocity']}" scope="parent"/>
        <xacro:property name="max_effort" value="${steering_properties['max_effort']}" scope="parent"/>
        
        <xacro:property name="base_mass" value="${base_density * base_length * base_height * base_width}" scope="parent"/>
        <xacro:property name="wheel_separation" value="${base_width + wheel_width}" scope="global"/>
        <xacro:property name="wheel_offset" value="${base_length/2 - wheel_radius}" scope="parent"/>
        <xacro:property name="wheel_mass" value="${wheel_density * pi * wheel_radius * wheel_radius * wheel_width}" scope="parent"/>
        <xacro:property name="max_wheel_angular_velocity" value="${max_velocity / wheel_radius}" scope="parent"/>
    </xacro:macro>

    

</robot>