<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find ackermann_vehicle_description)/urdf/common_properties.xacro"/>
    
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <xacro:cylinder_inertia r="${wheel_radius}" l="${wheel_width}" m="${wheel_mass}" o_xyz="0.0 0.0 0.0" o_rpy="${pi / 2.0} 0.0 0.0"/>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/ 2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/ 2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>    

    <xacro:macro name="ackermann_vehicle" params="robot_parameters_file"> 
        <!-- Load configuration data from the provided .yaml files -->
        <xacro:read_model_data robot_parameters_file="${robot_parameters_file}"/>

        <link name="base_footprint"/>

        <link name="base_link">
            <xacro:box_inertia l="${base_length}" w="${base_width}" h="${base_height}" m="${base_mass}" o_xyz="0.0 0.0 ${base_height / 2.0}" o_rpy="0.0 0.0 0.0"/>
            <visual>
                <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                    <!-- <box size="0.3 0.18 0.05"/> -->
                </geometry>
                <material name="green"/>            
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                    <!-- <box size="0.3 0.18 0.05"/> -->
                </geometry>
            </collision>
            
        </link>

        <xacro:wheel_link prefix="rear_right"/>
        <link name="front_right_steering_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="1.570795 0.0 0.0"/>
                <geometry>
                    <cylinder length="0.001" radius="0.01"/>
                </geometry>
                <material name="wheel_material">
                    <color rgba="0.0 0.0 0.0 1.0"/>
                </material>
                </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="1.570795 0.0 0.0"/>
                <geometry>
                    <cylinder length="0.001" radius="0.01"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.01"/>
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
                <origin xyz="0.0 0.0 0.0" rpy="1.570795 0.0 0.0"/>
            </inertial>
        </link>
        <xacro:wheel_link prefix="front_right"/>
        <xacro:wheel_link prefix="rear_left"/>
        <link name="front_left_steering_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="1.570795 0.0 0.0"/>
                <geometry>
                    <cylinder length="0.001" radius="0.01"/>
                </geometry>
                <material name="wheel_material">
                    <color rgba="0.0 0.0 0.0 1.0"/>
                </material>
                </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="1.570795 0.0 0.0"/>
                <geometry>
                    <cylinder length="0.001" radius="0.01"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.01"/>
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
                <origin xyz="0.0 0.0 0.0" rpy="1.570795 0.0 0.0"/>
            </inertial>
        </link>
        <xacro:wheel_link prefix="front_left"/>

        <joint name="base_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
        </joint>

        <joint name="rear_right_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="rear_right_wheel_link"/>
            <origin xyz="-${wheel_offset} ${-wheel_separation/2} 0.0" rpy="0.0 0.0 0.0"/>
            <axis xyz="0 1 0"/>
            <limit effort="${max_effort}" velocity="${max_wheel_angular_velocity}"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <joint name="front_right_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="front_right_steering_link"/>
            <origin xyz="${wheel_offset} ${-wheel_separation/2} 0.0" rpy="0.0 0.0 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="${max_steering_effort}" lower="${-max_steering_angle}" upper="${max_steering_angle}" velocity="${max_steering_angular_velocity}"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <joint name="front_right_wheel_joint" type="continuous">
            <parent link="front_right_steering_link"/>
            <child link="front_right_wheel_link"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <axis xyz="0 1 0"/>
            <limit effort="${max_effort}" velocity="${max_wheel_angular_velocity}"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <joint name="rear_left_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="rear_left_wheel_link"/>
            <origin xyz="-${wheel_offset} ${wheel_separation/2} 0.0" rpy="0.0 0.0 0.0"/>
            <axis xyz="0 1 0"/>
            <limit effort="${max_effort}" velocity="${max_wheel_angular_velocity}"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <joint name="front_left_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="front_left_steering_link"/>
            <origin xyz="${wheel_offset} ${wheel_separation/2} 0.0" rpy="0.0 0.0 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="${max_steering_effort}" lower="${-max_steering_angle}" upper="${max_steering_angle}" velocity="${max_steering_angular_velocity}"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <joint name="front_left_wheel_joint" type="continuous">
            <parent link="front_left_steering_link"/>
            <child link="front_left_wheel_link"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <axis xyz="0 1 0"/>
            <limit effort="${max_effort}" velocity="${max_wheel_angular_velocity}"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

    </xacro:macro>

</robot>