controller_manager:
  ros__parameters:

    update_rate: 250 #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 250.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true
    # constraints:
    #   stopped_velocity_tolerance: 0.2
    #   goal_time: 0.0
    #   shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
    #   shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
    #   elbow_joint: { trajectory: 0.2, goal: 0.1 }
    #   wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
    #   wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
    #   wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
      
forward_velocity_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5