<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.05"/>
    <xacro:property name="lidar_length" value="0.05"/>

    <link name="lidar_link">
        <xacro:cylinder_inertia r="${lidar_radius}" l="${lidar_length}" m="0.05" o_xyz="0 0 0" o_rpy="0 0 0"/>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.0 0.0 ${base_height+lidar_length/2}" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <gazebo reference="lidar_link">
        <sensor name="lidar" type="gpu_lidar">
            <always_on>true</always_on>
            <pose>0 0 0 0 0 0</pose>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <topic>/scan</topic>
            <gz_frame_id>lidar_link</gz_frame_id>
            <!-- <frame_id>lidar_link</frame_id> -->
            <lidar>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-2.3562</min_angle>
                        <max_angle>2.3562</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </lidar>
            <!-- <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
                <render_engine>ogre2</render_engine>
            </plugin> -->
        </sensor>
    </gazebo>
</robot>