<?xml version="1.0" encoding="UTF-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <xacro:cylinder_inertia r="${wheel_radius}" l="${wheel_length}" m="1.0" o_xyz="0.0 0.0 0.0" o_rpy="${pi / 2.0} 0.0 0.0"/>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="grey"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <link name="base_footprint"/>
    
    <link name="base_link">
        <xacro:box_inertia l="${base_length}" w="${base_width}" h="${base_height}" m="5.0" o_xyz="0.0 0.0 ${base_height / 2.0}" o_rpy="0.0 0.0 0.0"/>
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
    </link>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <link name="caster_wheel_link">
        <xacro:sphere_inertia r="${wheel_radius / 2.0}" m="0.5" o_xyz="0.0 0.0 0.0" o_rpy="0.0 0.0 0.0"/>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${-(base_width+wheel_length) / 2.0} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-base_length / 4.0} ${(base_width+wheel_length) / 2.0} 0" rpy="0 0 0"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length / 3.0} 0.0 ${-wheel_radius / 2.0}" rpy="0.0 0.0 0.0"/>
    </joint>
    
</robot>