<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="lidar_radius" value="0.05"/>
    <xacro:property name="lidar_length" value="0.05"/>
    <!-- Hokuyo Laser -->
    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="1e-5" r="${lidar_radius}" l="${lidar_length}" o_xyz="0.0 0.0 0.0" o_rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <axis xyz="0 0 1" />
        <origin xyz="0 0 ${base_height + lidar_length / 2.0}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="lidar_link">
        <sensor type="gpu_lidar" name="lidar_sensor">
            <always_on>true</always_on>
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>15</update_rate>
            <topic>scan</topic>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <!-- <min_angle>-1.570796</min_angle>
                        <max_angle>1.570796</max_angle> -->
                        <min_angle>-2.094395</min_angle>
                        <max_angle>2.094395</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <!-- Noise parameters based on published spec for Hokuyo laser
                        achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                        stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                        reading. -->
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </lidar>

            <!-- Gazebo plugin to publish the laser scan data -->
            <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
                <render_engine>ogre2</render_engine>
            </plugin>  
        </sensor>
    </gazebo>
</robot>